import type { ActivityEvent, Bounty, Capability, Metrics, Treasury } from './types';

export const demoMetrics: Metrics = {
  paidJobs: 12,
  settlementPending: 0,
  settlementPendingOldestSeconds: null,
  deliveredPrs: 9,
  mergedPrs: 7,
  refundCount: 3,
  refundPending: 0,
  refundPendingOldestSeconds: null,
  refundSuccessRate: 1,
  externalRepositories: 4,
  externalMaintainers: 3,
  settledCustomerReceiptsUsd: 86,
  recognizedRevenueUsd: 66,
  platformReportedCreatorFeesSentLamports: '820000000',
  variableRouteCostEstimateUsd: 24.18,
  recognizedRevenueLessVariableRouteEstimateUsd: 41.82,
  grossMarginStatus: 'unverified',
  costCoverage: {
    included: [
      'gateway_model_token_rate_estimate',
      'gateway_sandbox_runtime_estimate',
      'reviewer_model_token_rate_estimate',
    ],
    excluded: ['provider_billing_adjustments', 'chain_and_facilitator_fees', 'infrastructure'],
  },
  bountiesCreated: 3,
  bountiesOpen: 1,
  bountiesUnfundedOpen: 0,
  bountiesClaimed: 1,
  bountiesReleased: 1,
  externalContributors: 2,
  activeCapabilities: 1,
  refundProtection: {
    status: 'verified',
    source: 'policy_signer_finalized',
    refundTreasury: 'H3xYkQ9xwVcpKH7E5uAxQRnMivVRVDJefFZ3vVjCjU7x',
    refundMint: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
    refundDecimals: 6,
    finalizedBalanceAtomic: '184720000',
    signerOutstandingLiabilityAtomic: '20000000',
    unencumberedBalanceAtomic: '164720000',
    newIntakeCapacityAtomic: '100000000',
    remainingDailyLimitUsdCents: 10_000,
    localOutstandingLiabilityAtomic: '20000000',
    liabilityReconciled: true,
    liabilitiesBacked: true,
    checkedAt: '2026-08-22T16:42:00.000Z',
  },
  recordedNetFlowUsd: 184.72,
  plannedImprovementAllocationUsd: 70,
  plannedResearchAllocationUsd: 30,
  allocationTargetsSatisfied: true,
  updatedAt: '2026-08-22T16:42:00.000Z',
};

export const demoBounties: Bounty[] = [
  {
    id: 'bty_01J59K4A8Y',
    title: 'Preserve comments when normalizing a YAML workflow',
    repository: 'public-tools/release-workflows',
    issueUrl: 'https://github.com/public-tools/release-workflows/issues/184',
    issueNumber: 184,
    amountUsd: 20,
    amountAtomic: '100000000',
    asset: 'SOL',
    state: 'open',
    failureClass: 'structured_edit',
    acceptanceCriteria: [
      'Keep existing comments and key ordering',
      'Pass the repository test suite',
      'Limit changes to the workflow parser',
    ],
    customerRefundTransaction: '5zPHjkGCzRuAoeM5DsPqWK7DUJqbcSW6F7o2UQmZdP6G',
    escrowTransaction: '2PNd9mDftgpcFec3yqW1A6EjtY4MQv3oJqUqJ2o5ZzPA',
    createdAt: '2026-08-22T14:28:00.000Z',
    updatedAt: '2026-08-22T14:33:00.000Z',
  },
  {
    id: 'bty_01J59HBQ9M',
    title: 'Repair Windows path handling in cache cleanup',
    repository: 'tiny-ci/cache-tools',
    issueUrl: 'https://github.com/tiny-ci/cache-tools/issues/91',
    issueNumber: 91,
    amountUsd: 10,
    amountAtomic: '50000000',
    asset: 'SOL',
    state: 'claimed',
    failureClass: 'platform_specific_test',
    acceptanceCriteria: [
      'Cover drive-letter and UNC paths',
      'Retain POSIX behavior',
      'Pass a separate AI review',
    ],
    customerRefundTransaction: '7Kp3bZvM1aYq6uFc4hT9dR2sNx8wE5jL3gP7vQmC2aHs',
    escrowTransaction: '8Mr4cAwN2bZr7vGd5iU1eS3tPy9xF6kM4hQ8wRnD3bJt',
    claimant: { github: 'river-builds', wallet: '6Ztq1RHq3M5v9VbXj21cTy9RkL7A9yAvS6FMbP3mKaE2' },
    claimExpiresAt: '2026-08-23T10:00:00.000Z',
    createdAt: '2026-08-21T09:11:00.000Z',
    updatedAt: '2026-08-22T10:00:00.000Z',
  },
  {
    id: 'bty_01J5846T3K',
    title: 'Add regression coverage for stale lock cleanup',
    repository: 'open-maintainers/pkg-guard',
    issueUrl: 'https://github.com/open-maintainers/pkg-guard/issues/42',
    issueNumber: 42,
    amountUsd: 10,
    amountAtomic: '50000000',
    asset: 'SOL',
    state: 'released',
    acceptanceCriteria: [
      'Reproduce the failure',
      'Add a focused regression test',
      'Keep the patch under three files',
    ],
    claimant: { github: 'patch-lab' },
    customerRefundTransaction: '9Ns5dBxP3cAs8wHe6jV2fT4uQz1yG7mN5iR9xSpE4cKu',
    escrowTransaction: '3Qv6eCyR4dBt9xJf7kW3gU5vSa2zH8nP6jT1yMqF5dLv',
    pullRequestUrl: 'https://github.com/open-maintainers/pkg-guard/pull/47',
    releaseTransaction: '4EqM3NYNMyM8pAENd3FAWVbCcYyoRh1mNaRH8dbtP1kW',
    createdAt: '2026-08-19T08:30:00.000Z',
    updatedAt: '2026-08-20T15:17:00.000Z',
  },
];

export const demoTreasury: Treasury = {
  refundProtection: demoMetrics.refundProtection,
  recordedInflowsUsd: 218.9,
  recordedOutflowsUsd: 34.18,
  recordedNetFlowUsd: 184.72,
  localOutstandingLiabilityUsd: 20,
  plannedRunwayDays: 43,
  allocationModel: {
    source: 'application_ledger',
    custodyVerified: false,
    modeledFundsUsd: 184.72,
    targetsSatisfied: true,
    refundTargetUsd: 50,
    refundAllocationUsd: 50,
    operatingTargetUsd: 34.72,
    operatingAllocationUsd: 34.72,
    plannedImprovementAllocationUsd: 70,
    plannedResearchAllocationUsd: 30,
    policy: {
      refundTargetMinimumUsd: 50,
      operatingTargetMinimumUsd: 25,
      improvementShare: 0.7,
      researchShare: 0.3,
    },
    buckets: [
      {
        id: 'refund_target',
        label: 'Planned refund allocation',
        allocatedUsd: 50,
        targetUsd: 50,
      },
      {
        id: 'operating_target',
        label: 'Planned operating allocation',
        allocatedUsd: 34.72,
        targetUsd: 34.72,
      },
      {
        id: 'improvement_plan',
        label: 'Planned improvement allocation',
        allocatedUsd: 70,
      },
      {
        id: 'research_plan',
        label: 'Planned AI-provider research allocation',
        allocatedUsd: 30,
      },
    ],
  },
  ledger: [
    {
      id: 'led_01',
      type: 'customer_receipt',
      amountUsd: 10,
      direction: 'credit',
      description: 'Standard maintenance job settled',
      transaction: '3taZ74j1ArW3u8C9GMMNTfXsY7bGmRksYbFgrwEa3aAa',
      occurredAt: '2026-08-22T16:42:00.000Z',
    },
    {
      id: 'led_02',
      type: 'bounty_funding',
      amountUsd: 20,
      amountAtomic: '100000000',
      asset: 'SOL',
      direction: 'debit',
      description: 'Maintenance-bounty escrow funded',
      transaction: '2PNd9mDftgpcFec3yqW1A6EjtY4MQv3oJqUqJ2o5ZzPA',
      occurredAt: '2026-08-22T14:33:00.000Z',
    },
    {
      id: 'led_03',
      type: 'refund',
      amountUsd: 10,
      direction: 'debit',
      description: 'Customer refunded in full',
      transaction: '5zPHjkGCzRuAoeM5DsPqWK7DUJqbcSW6F7o2UQmZdP6G',
      occurredAt: '2026-08-22T14:29:00.000Z',
    },
  ],
  updatedAt: '2026-08-22T16:42:00.000Z',
};

export const demoCapabilities: Capability[] = [
  {
    id: 'cap_structured_edits',
    name: 'Structure-preserving edits',
    description: 'Modify YAML and JSON without destroying comments or stable ordering.',
    state: 'funded',
    category: 'code transformation',
    benchmarkBefore: 61,
    benchmarkUnit: '% pass',
    updatedAt: '2026-08-22T14:33:00.000Z',
  },
  {
    id: 'cap_cross_platform',
    name: 'Cross-platform path repair',
    description: 'Test and repair path behavior across Linux, macOS, and Windows.',
    state: 'validating',
    category: 'validation',
    benchmarkBefore: 72,
    benchmarkAfter: 94,
    benchmarkUnit: '% pass',
    evidenceUrl: 'https://github.com/mizuki-agent/mizuki/pull/18',
    updatedAt: '2026-08-22T10:00:00.000Z',
  },
  {
    id: 'cap_test_scoping',
    name: 'Repository-aware test selection',
    description: 'Choose the smallest validation set that still covers the submitted issue.',
    state: 'active',
    category: 'execution',
    benchmarkBefore: 38,
    benchmarkAfter: 82,
    benchmarkUnit: '% relevant',
    evidenceUrl: 'https://github.com/mizuki-agent/mizuki/pull/11',
    activatedAt: '2026-08-20T15:17:00.000Z',
    updatedAt: '2026-08-20T15:17:00.000Z',
  },
];

export const demoActivity: ActivityEvent[] = [
  {
    id: 'evt_01',
    kind: 'job_paid',
    title: 'Standard job paid',
    description: 'public-tools/release-workflows · issue #184',
    amountUsd: 10,
    transaction: '3taZ74j1ArW3u8C9GMMNTfXsY7bGmRksYbFgrwEa3aAa',
    occurredAt: '2026-08-22T14:21:00.000Z',
  },
  {
    id: 'evt_02',
    kind: 'refund_completed',
    title: 'Full refund finalized',
    description:
      'The coding attempt did not pass validation. The quoted USDC payment was returned in full.',
    amountUsd: 10,
    transaction: '5zPHjkGCzRuAoeM5DsPqWK7DUJqbcSW6F7o2UQmZdP6G',
    occurredAt: '2026-08-22T14:29:00.000Z',
  },
  {
    id: 'evt_03',
    kind: 'bounty_opened',
    title: 'Funded maintenance bounty published',
    description: 'A maintenance bounty with approximately $20 in escrowed SOL is open.',
    amountUsd: 20,
    href: '/bounties/bty_01J59K4A8Y',
    transaction: '2PNd9mDftgpcFec3yqW1A6EjtY4MQv3oJqUqJ2o5ZzPA',
    occurredAt: '2026-08-22T14:33:00.000Z',
  },
  {
    id: 'evt_04',
    kind: 'pull_request_merged',
    title: 'Maintenance pull request merged',
    description: 'open-maintainers/pkg-guard · pull request #47',
    href: 'https://github.com/open-maintainers/pkg-guard/pull/47',
    occurredAt: '2026-08-20T15:14:00.000Z',
  },
  {
    id: 'evt_05',
    kind: 'capability_activated',
    title: 'New capability activated',
    description: 'Repository-aware test selection improved from 38% to 82%.',
    href: '/capabilities',
    occurredAt: '2026-08-20T15:17:00.000Z',
  },
];
