[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
settlement = "cov9UDypG7nsryxdgMcKhKU2spRVWLVjxT2iTv6do5Y"

[programs.devnet]
settlement = "cov9UDypG7nsryxdgMcKhKU2spRVWLVjxT2iTv6do5Y"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/settlement"]
types = "target/types"
