[package]
name = "covenant-settlement-program"
version = "0.1.0"
description = "Covenant Solana protocol program for external COVNT staking, credits, escrow, and receipt anchors."
edition = "2021"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "lib"]
name = "covenant_settlement_program"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = "0.31.1"
anchor-spl = "1.0.2"
